### ISSUE TITLE
Artifact effect descriptions don't update after 'optimizing all artifacts from storage'.

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#12]
**Describe the bug**
The descriptions of the artifact set bonuses on the bottom right don't update after optimizing all artifacts from storage. It's only the description that doesn't change, the numbers are all correct.

**To Reproduce**
1. Start any new build.
2. Optimize all artifacts from storage.
3. Scroll down to 'Artifact Effects'
4. It'll still show the previous artifact effects.

**Expected behavior**
It should update to the new artifact descriptions.

**Screenshots**
![image](https://user-images.githubusercontent.com/77327291/104336507-c5125b00-54f4-11eb-8c45-728ca1f4d34d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome
 - Version 87.0.4280.141

**Additional context**
It's an issue that only concerns the new alpha of the calculator.

**Comment by JenShin-368** [comment]
Fixed.
