### ISSUE TITLE
Clarification on a Leaked Weapon and Set

### ISSUE THREAD

**Issue by OJofSteel** [JenShin-368/GenshinImpactCalculator#128]
I wanted some clarification on the reason behind including two leaked items in your damage calculator.

The two leaked items are: Dreams of Dragonfell, a bow; and Icebreaker, an artifact set.
![image](https://user-images.githubusercontent.com/71749922/143660423-6d19cd94-3f71-499f-baf7-0f1fa04b8dc9.png)
![image](https://user-images.githubusercontent.com/71749922/143660437-fcb6598b-09a1-4d23-ba9a-7a1bca659df3.png)

I understand these leaked items are quite old, but a leak is still a leak no matter how old it is. If you don't plan on removing the leaked items, is there a particular reason why?

**Comment by JenShin-368** [comment]
If they are leaked then it's likely unintentional.  Could be scraped unintentionally from wiki or something will take a look.  However icebreaker seems to be released though the naming might be different.
