### ISSUE TITLE
Noelle Constellation 4 effect shows 40% ATK instead of 400% ATK

### ISSUE THREAD

**Issue by Minitte** [JenShin-368/GenshinImpactCalculator#13]
**Describe the bug**
When viewing Noelle's damage dealt with her 4th constellation, the damage displayed equals 40% of her ATK instead of 400%.

> Constellation 4: To Be Cleaned: "When Breastplate ends or shatters, it deals 400% of ATK as Geo DMG to surrounding opponents."
-https://genshin-impact.fandom.com/wiki/Noelle

**To Reproduce**
1. Create a slot for Noelle.
2. Set Noelle's constellation to 4 or higher.
3. View the damage listed under Noelle's 4th constellation "To Be Cleaned".

**Expected behavior**
The damage calculation should be:
- When Breastplate ends or shatters, it deals **400%** of ATK as Geo DMG to surrounding opponents.

Instead of:
- When Breastplate ends or shatters, it deals **40%** of ATK as Geo DMG to surrounding opponents.

**Screenshot**
![noelle 40 400](https://user-images.githubusercontent.com/19943415/104405119-1597b180-5511-11eb-9e2c-18c6ccc91f78.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox 
 - Version 84.0.2 (64-bit)

**Additional context**
I suck at math so maybe it's wrong.
(DMG / (1 + GEO%)) / ATK = Current damage scaling
According to screenshot: (46 / (1 + 0)) / 115 = 0.4 (40%)

**Comment by SiriusGreyhound** [comment]
Hey, thanks for letting us know. We're going to verify it and then fix it if it's really wrong.

**Comment by SiriusGreyhound** [comment]
`"When Breastplate&#39s duration expires or it is destroyed by DMG, it will deal 400% ATK of Geo DMG to surrounding enemies.",calcStats:[{stat:"Expiration DMG",damage:e=>.4,damageType:"ElementalSkillDMG",damageElement:"GeoDMG"}]};`
I found the corresponding code and it does indeed have a 0.4 multiplier there. I don't have C4 Noelle, so I can't do any actual tests to compare values between the calculator and in game values.

**Comment by JenShin-368** [comment]
Fixed.
