### ISSUE TITLE
Ganyu Bugs

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#14]
**Two Ganyu Bugs that need fixing**
1. Ganyu's Normal Attacks are effected by Gladiator 4-piece set bonus even though she uses a bow.
2. Ganyu's burst Energy Cost is 60, not 80
3. Loading a Ganyu Build Results in 0s for Frostflake Arrow and Bloom Damage. Nothing I did seemed to fix this.

I already confirmed these.

**Comment by JenShin-368** [comment]
1. Gladiator 4-piece doesn't check if user uses bow. Until there's a revamp of the calculator's engine, it's up to the user not to use 4-piece gladiator. <-- should be coming soon/before the artifact db is out

2. fixed
3. fixed
