### ISSUE TITLE
Saving more than 30 Artifacts = bad things happen

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#22]
**The Problem**
The artifact storage system breaks if there's more than 30 artifacts in the storage.

**Expected behavior**
Restriction of 30 artifacts which doesn't allow you to save more than 30 with clear message and prior documentation. Maybe a small x/30 somewhere so you know how many are allowed. 

**Monetization**
Perhaps we could offer people premium accounts for 1$ a month for more storage. Ten for standard user, 50 for premium.

**Comment by JenShin-368** [comment]
should be fixed.
