### ISSUE TITLE
Optimize Set Effects often favors unsuitable artifacts

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#24]
**Describe the bug**
When using the optimize set effects button it sometimes favors unsuitable sets like 4-piece thundersoother, because it toggles the 4-set bonus when running these calculations

**Effected sets (list not complete yet)**
- Thundersoother
- Lavawalker
- Retracing Bolide

**Possible Fixes**
Edits Following

**Comment by JenShin-368** [comment]
Fixed
