### ISSUE TITLE
Albedo C2 Burst Damage Bug

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#25]
**Describe the bug**
The burst Damage for C2 Albedo isn't being calculated correctly if compared to in game numbers.

**Reference**
https://www.reddit.com/r/Albedomains/comments/kyg3yj/possible_bug_with_c2_need_more_people_to_test

**Additional context**
I've already dug around, but couldn't figure out why the calculator is getting things wrong. It may have to do with the 50% damage reduction on same level targets being wrong somehow.

The discord user who brought up this issue was Drago#2945

**Comment by SiriusGreyhound** [comment]
*from toranix via /r/Albedomains sent 16 hours ago
I had a hunch just now and I figured out what was wrong with the site's formula after some basic number-crunching on it.

They calculate the amount of DEF to add to the burst based on the stack count correctly, but then take that number, add it to ATK and multiply the entire thing by the ATK scaling modifier of the burst. Only ATK should be affected by that modifier, the DEF scaling from C2 is a separate addition, and then the two are combined before applying crit/damage bonus/resistance since both are subject to each of those.

That is, their current formula is (incorrectly):

(DEF * 30% * Stacks + ATK) * Burst ATK Modifier * Dmg Bonuses * Crit * Damage Reduction * Resistance Modifier

When it should be:

(ATK * Burst ATK Modifier + DEF * 30% * Stacks) * Dmg Bonuses * Crit * Damage Reduction * Resistance Modifier*

**Comment by JenShin-368** [comment]
Fixed.

**Comment by SiriusGreyhound** [comment]
Re-Opened, because the same user reported that on top of burst his transient blossom damage is also off now.

> The numbers are still off.
Burst DMG: DmgCalc = non-crit 7565 / crit 16976
Burst DMG: In Game = non-crit 8270 / crit 18561
Fatal Blossom DMG: DMGCalc = non-crit 2112 / crit 4738
Fatal Blossom DMG: In Game = non-crit 2818 / crit 6325

They're using a manual formula they got from r/albedomains which gets them closer to their in game numbers.

> Here is what i get.
lvl 90 with burst at lvl 6
ATK = 1536
DEF = 1444
GeoDmg = 90.4
Crit Dmg = 124.4
Dmg Reduction lvl 89 Fatui Pyro Agent:  (100+90)/(200+90+89) = 0.5013
Dmg Resistance lvl 89 Fatui Pyro Agent: 10% Geo 
formula:
((((((1536 x 514.08%) + ((1444 x 30%) x 4))) x 190.4%) x 224.4%) x 49.87%) x 90%) = 18465.28
In game burst dmg crit = 18561
The formula is definately closer to the in game number.  If i am doing something wrong with the dmg reduction or dmg resistance let me know.
The other formula was giving me nearly identical numbers to what the calculator was giving me before the update you guys did.
What we think the calculator's formula was:
((((((((1444 x 30%) x 4) + 1536) x 514.08%) x 190.4%) x 224.4%) x 49.87%) x 90%) = 32224.84

**Comment by JenShin-368** [comment]
fixed.
