### ISSUE TITLE
Tartaglia melee charged attack with Rust bug

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#28]
**Describe the bug**
1. Rust's bonus normal attack damage increases Tartaglia's melee charged attack damage.
2. Rust doesn't decreases Tartaglia's melee charged attack damage.

**Expected behavior**
1. [ ] Rust's bonus normal attack damage does not increases Tartaglia's melee charged attack damage.
2. [ ] Rust does decreases Tartaglia's melee charged attack damage.

**Additional context**
This bug was reported by discord user Mahazael#2135

**Comment by JenShin-368** [comment]
fixed.
