### ISSUE TITLE
Kaeya's constellation not using appropriate stats 

### ISSUE THREAD

**Issue by lunaras13** [JenShin-368/GenshinImpactCalculator#31]
**Describe the bug**
you currently have Kaeya's C1 passive that adds crit rate against cryo effected units adding flat crit rate. It should only be applying this to his basic and charged attack, not plunge attack, E, or Q.

**To Reproduce**
1. apply blizzard strayer artifacts (no substat crit rate)
2. apply a black sword that is lvl 80 (25.1% crit rate)
3. apply frozen to enemy to calculate overall crit rate total to be 85.1%
4. look at his normal attack, skill, and burst each have non-crit, crit, and average be different numbers
5. toggle on excellent blood 
6. see the normal attack, skill, and burst average become the same as crit

**Expected behavior**
only giving the crit rate to basic and charged attack

**Comment by JenShin-368** [comment]
fixed.
