### ISSUE TITLE
Sword of Descension ATK Value

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#32]
**Describe the bug**
The main ATK for Sword of Descension aren't right.

**Expected behavior**
![image](https://user-images.githubusercontent.com/77327291/105013123-32ffda80-5a3f-11eb-817c-f0744e977527.png)

**Additional context**
This bug was reported by discord user Tansami Jurma#0229

**Comment by JenShin-368** [comment]
fixed.
