### ISSUE TITLE
DPS Value unchanged in Reaction Mode

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#34]
**Describe the bug**
When using a character that has their normal attacks converted into elemental damage the reaction mode doesn't effect the DPS value.

**Expected behavior**
When using a character that has their normal attacks converted into elemental damage the reaction mode effects the DPS value.

**Screenshots**
![image](https://user-images.githubusercontent.com/77327291/105220703-608c7700-5b58-11eb-9e23-0e7c0615dfcc.png)

**Additional context**
Bug reported by discord user Victorey84#4835

**Comment by JenShin-368** [comment]
Fixed.
