### ISSUE TITLE
Artifact presets

### ISSUE THREAD

**Issue by Bobrokrot** [JenShin-368/GenshinImpactCalculator#35]
**Is your feature request related to a problem? Please describe.**
It'd be great to have a quick way to equip pre-set Artifact sets and substats instead of tedious clicking through every single artifact option.

**Describe the solution you'd like**
1) I'd like a button to quickly equip arifacts sets, like equip full Gladiator set.
2) A button to +16 and +20 all artifacts.
3) Buttons to set main states to pre-sets of ATK/Elem%/CR on sands/goblet/circlet, EM/Elem%/CRIT, same options with CDMG instead of CRIT, full EM etc.
4) Presets of artifact substats. Average substats among all artifacts that rolled evenly amond def, hp, em, ark, crit, ER etc. And maybe also "bad substats" that rolled mostly into defense.

**Comment by SiriusGreyhound** [comment]
Thank you for your suggestion,
but we're not going to implement this. But there's other solutions that we are considering.
