### ISSUE TITLE
Reaction Mode breaks artifact estimation

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#37]
https://youtu.be/7dXLcgr_xVM?t=1544

Turning on the reaction mode skews up the estimated improvement or downgrade and artifact has in the 'load artifact' screen. It seems like it doesn't update when reaction mode is toggled.

**Comment by JenShin-368** [comment]
I was unable to replicate this bug. After watching the video a couple of times, it looks like the reaction mode prediction still updating. However, by saving/loading the optimizer target is reset to "Default" so it appears as if the reaction mode predictions were wrong b/c saving/loading changes the predictions. Can you confirm whether this is the case or not?

**Comment by JenShin-368** [comment]
I was unable to replicate this bug. After watching the video a couple of times, it looks like the reaction mode prediction still updating. However, by saving/loading the optimizer target is reset to "Default" so it appears as if the reaction mode predictions were wrong b/c saving/loading changes the predictions. Can you confirm whether this is the case or not?

**Comment by SiriusGreyhound** [comment]
Before turning on reaction mode
![image](https://user-images.githubusercontent.com/77327291/105985145-6247c480-609b-11eb-866c-dd48749ae099.png)

After turning on reaction mode
![image](https://user-images.githubusercontent.com/77327291/105985226-7986b200-609b-11eb-8cca-1f26d44a34f5.png)

As you can see in the second screenshot, when reaction mode is turned on the % values do not make sense anymore. The artifact that is worn should have 0%, since nothing changes when you put it on. So the information provided is not correct. Putting it on does not provide 26.32% improvement, it provides 0%, because it's the same artifact you already have on.

**Comment by JenShin-368** [comment]
Fixed. It looks like the predictor wasn't caching the reaction proc chance.

As for the issue with Diluc, I'm not sure what the bug is there. If you can replicate it we should open another issue for it.
