### ISSUE TITLE
Invalid Name bug on artifact storage

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#42]
**Describe the bug**
When trying to save an artifact with an invalid name, there will be a popup notifying about the invalid name. The problem happens after, because afterwards artifacts cannot be saved no matter what name you enter and it only works if you reload the page. The console is empty.

**Expected behavior**
'Saving' as with a valid name should save the artifact, even if you tried an invalid name before that.

**Additional context**
Bug reported by discord user ClouduSan#7342

**Comment by JenShin-368** [comment]
Fixed
