### ISSUE TITLE
Ningguang Charged Attack 1

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#44]
**Describe the bug**
Ningguang's Charged Attack 1 has been fixed in game so it scales with Geo DMG % now and the calculator does not actually scale it with Geo DMG%.

**Expected behavior**
Charged Attack 1 to scale with Geo DMG%

**Additional context**
This bug was reported by discord user Chloroplaste#3089

**Comment by JenShin-368** [comment]
fixed.
