### ISSUE TITLE
Skyward Blade Weapon Bonus is Wrong

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#45]
**Describe the bug**
The Skyward Blade (1h Sword) is slightly wrong on the calculator currently. It adds % on normal and charged attacks when actually it procs another line of damage per hit, similar to Skyward Pride. I don't know if there is an internal cooldown, or if it is with every attack. Also not sure if it procs on charged attacks

**Expected behavior**
- [ ] Have the damage be added as additional DPS and then get a total DPS value.
- [ ] Update the description of the weapon.

**Additional context**
The bug was reported by discord user Daddy Issues#1955 and I've already asked them to give more details on how the effect actually works in game.

**Comment by JenShin-368** [comment]
Fixed.
