### ISSUE TITLE
disabling enemy calc does not reset resistances

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#49]
**Describe the bug**

**To Reproduce**
1. amber Lv1 overload: **34 damage** (enemy calc is off, enemy is "None", all RES are 0)
2. select Hilichurl: all RES get set to 10 (overloaded damage does not change, as intended)
3. enable enemy calc: overload **31 damage** (as intended)
4. **disable enemy calc:** overload **31 damage** (not intended)

**Expected behavior**
- [x] Turning off enemy calc should negate resistance calculations.

**Additional context**
Report by discord user iluvredwall#4807

**Comment by JenShin-368** [comment]
Fixed.
