### ISSUE TITLE
Improve adding artifacts

### ISSUE THREAD

**Issue by IlluminatusII** [JenShin-368/GenshinImpactCalculator#50]
Сan you add using artifacts from the forum profile?

**Comment by JenShin-368** [comment]
I've never used the forum profile so I'm not sure. Please provide more information if you'd like to suggest an improvement.

**Comment by IlluminatusII** [comment]
Sorry, I was wrong character details inside the game
![image](https://user-images.githubusercontent.com/58222103/107112730-91202080-687b-11eb-9dd0-9bde7a9421e9.png)
