### ISSUE TITLE
Primordial Jade Cutter Values Wrong

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#51]
**Describe the bug**
The ATK and Crit Rate of the sword are wrong in some cases.

**Screenshots**
![image](https://user-images.githubusercontent.com/77327291/107130529-922e6d80-68ce-11eb-8689-0b9d09ed9f93.png)
*Screenshot of actual stats.*

**Additional context**
Issue reported by discord user Winter#8881

**Comment by JenShin-368** [comment]
Fixed.
