### ISSUE TITLE
Bug on Load Build

### ISSUE THREAD

**Issue by P2PSelfPuppet** [JenShin-368/GenshinImpactCalculator#52]
**Describe the bug**
I saved a build named Xiao's Battery, the next day when I tried to load the build, it just won't load onto any slot. It also cannot be removed.

**To Reproduce**
1. Go to a character slot
2. Click on 'load build'
3. See error

**Expected behavior**
You won't be able to load the build or even delete it, not even replaced it help.

**Screenshots**
![Screenshot (52)](https://user-images.githubusercontent.com/78781562/107319577-0721c300-6ada-11eb-800f-a6b0730cf526.png)

As you can see, one of them cannot be removed and the other was created still.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome
 - Version: Latest

**Comment by SiriusGreyhound** [comment]
Hey there,
thanks for reporting this. Maybe it's an issue with the name containing a symbol. Could you include a screenshot of your console as well so we can see if there's any error? I'll try to reproduce it for now.

**Comment by P2PSelfPuppet** [comment]
![Screenshot (54)](https://user-images.githubusercontent.com/78781562/107460500-2fb9c380-6b93-11eb-8966-127470b44c32.png)

Is this good enough?

**Comment by SiriusGreyhound** [comment]
My bad, the console is something you can open in your browser that shows console logs.

![image](https://user-images.githubusercontent.com/77327291/107482913-9e415600-6b80-11eb-9f2a-7790ec67c460.png)

In Chrome you can use "Control + Shift + J" to open it directly.

**Comment by P2PSelfPuppet** [comment]
![Screenshot (55)](https://user-images.githubusercontent.com/78781562/107484201-0f066380-6bbd-11eb-9788-86cad85552b0.png)

This? Nothing happens with the log when I try to load Xiao's Battery, Xiao's Battery still won't load though, delete failed as usual.

**Comment by SiriusGreyhound** [comment]
Thank you. Now it's up to the developer to figure out what causes the problem. Too bad the console didn't yield any results.

**Comment by JenShin-368** [comment]
Fixed. That name was supposed to be invalid but the regex was bugged.

I've implemented a catch that will resolve bugged names. Highly recommend deleting the build and renaming it to something that's valid.
