### ISSUE TITLE
Xingqiu C4 Bug

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#54]
**Describe the bug**
Xingiu's E was confirmed to be a separate 50% damage multiplier, not added into the DMG% multiplier

**Discord Discussion**
[https://discord.com/channels/787335702182494218/787335785795813376/808984789780529173](url)

**Screenshots**
![image](https://user-images.githubusercontent.com/77327291/107490161-caada000-6b89-11eb-9076-b5bcc4301c9e.png)

C4 Off
![image](https://user-images.githubusercontent.com/77327291/107490220-e153f700-6b89-11eb-8e90-8d7a934c034c.png)

C4 On
![image](https://user-images.githubusercontent.com/77327291/107490265-f3359a00-6b89-11eb-85a3-2d6a8ab39b1d.png)

**Additional context**
Issue and screenshots by discord user Luke#2499

**Comment by JenShin-368** [comment]
fixed.
