### ISSUE TITLE
Noelle optimizing for healing bug

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#56]
**Expected behavior**
Optimizing for Healing should work based on the defense.

**Screenshots**
![image](https://user-images.githubusercontent.com/77327291/108751559-ac10b700-7542-11eb-9df4-7f5361e891cb.png)

**Comment by SiriusGreyhound** [comment]
It happens for DMG Absorption too

**Comment by JenShin-368** [comment]
Fixed.
