### ISSUE TITLE
Wolf's Gravestone Passive

### ISSUE THREAD

**Issue by w44ves** [JenShin-368/GenshinImpactCalculator#57]
**Describe the bug**
The WGS 20% Bonus ATK passive seems to apply to the base atk and not after.

**Expected behavior**
I believe it's not supposed to take effect to the base atk directly, since it will scale higher after the atk% bonus from artifacts and ascension stats.

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Browser: Opera

**Comment by JenShin-368** [comment]
Need proof WGS functions differently from every other ATK% scaling item (normally, 20% ATK only applies to base).

**Comment by w44ves** [comment]
your WGS description in your site states that it increases BASE ATK, when it shouldn't. So what happens is it scales much bigger with the atk % bonus of the artifacts and WGS main stat. 
![Screenshot 2021-02-28 233358](https://user-images.githubusercontent.com/79624612/109424172-880b1500-7a1d-11eb-951c-88fc6f1f75bc.png)
![Screenshot 2021-02-28 233416](https://user-images.githubusercontent.com/79624612/109424173-8b060580-7a1d-11eb-920f-816bbda9bedc.png)

**Comment by JenShin-368** [comment]
Difference in description doesn't indicate anything. All description of ATK% in game is scaled off of base attack.

If you test it and you can show that the scaling is off of total atk as opposed to base atk, please provide evidence (since this is contrary to how every other item works).

**Comment by w44ves** [comment]
Sure thing! will be providing once I get my wgs to lvl 70, since the calc can't really specify weap levels between 10's. Appreciate the time!
