### ISSUE TITLE
Artifact Scan Mobile unable to drag screenshot.

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#58]
**Describe the bug**
On mobile it is impossible to drag your screenshot in the artifact scanner. 

**Expected behavior**
A method of dragging screenshots on mobile or other solution.

**Additional context**
Issue reported by discord user TheWizzlr#5907

**Comment by SiriusGreyhound** [comment]
Possibly this could be part of a larger problem of artifact storage optimization for mobile. On my phone it's not really well optimized. Parts of the artifact storage container are cut off and inaccessible.

**Comment by JenShin-368** [comment]
fixed.
