### ISSUE TITLE
Chongyun Skyward Pride Bug (general Skyward Pride Bug?)

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#60]
**Describe the bug**
There's a weird bug on chongyun that causes his Total DPS to be treated as Physical DMG, while wearing Skyward Pride, even when his passive is active. 

**To Reproduce**
https://genshinimpactcalculator.com/genshinCalc.html?shareID=N1aWtwn0MxtUKIhjlHr8

**Expected behavior**
Only the additional DMG from Skyward Pride is physical and should be effected by Physical Resistance on Enemies. Of course this is only relevant against enemies with physical or cryo resistances. As his total DPS would be wrong in either case.

**Screenshots**
![image](https://user-images.githubusercontent.com/77327291/109419775-68e59680-79cf-11eb-91ee-4b2b2be0dedb.png)

**Additional context**
Could be a general Skyward Pride bug.

**Comment by JenShin-368** [comment]
Fixed.
