### ISSUE TITLE
Noelle optimization issue: DMG Absorbtion

### ISSUE THREAD

**Issue by bagiran** [JenShin-368/GenshinImpactCalculator#67]
The Noelle's Dmg absorption depends on DEF stat only and it visible in the substats value window
![image](https://user-images.githubusercontent.com/11291143/110300510-fe081100-8007-11eb-9c58-b9d08282bb64.png)
But in the substats optimization section, I always have HP% substat instead of DEF%
![image](https://user-images.githubusercontent.com/11291143/110300721-445d7000-8008-11eb-844f-4835245a0404.png)
This happens for Circlet only.

**Comment by SiriusGreyhound** [comment]
Hey, does the Circlet have Def% as a mainstat? If so then HP is not actually relevant, it's just the go to option when there are no longer any valid results left. If the Def and Def% are both taken already then it will simply pick other substats. So this is not a bug.

**Comment by bagiran** [comment]
Yes, it has. I've got a point, sorry for the inconvenience.

**Comment by SiriusGreyhound** [comment]
It's no inconvenience. We're always grateful to anyone who wants to help identify bugs.
