### ISSUE TITLE
Primordial Jade Cutter | wrong crit% stats

### ISSUE THREAD

**Issue by rois0424** [JenShin-368/GenshinImpactCalculator#70]
**Describe the bug**
Primordial Jade Cutter secondary stat is showing 43.9% crit rate

**Expected behavior**
**Lvl 90 crit% stats should be 44.1%**, not 43.9%

**Screenshots**
![Screenshot 2021-03-09 225100](https://user-images.githubusercontent.com/70351792/110588745-52a3ad00-812a-11eb-8d30-9b34bce97e23.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Microsoft Edge
 - Version 89.0.774.45 (Official build) (64-bit)

**Comment by JenShin-368** [comment]
Fixed.
