### ISSUE TITLE
Hydro Elemental Resonance

### ISSUE THREAD

**Issue by Tetrakishexahedron** [JenShin-368/GenshinImpactCalculator#73]
**Describe the bug**
Soothing water elemental resonance only adds 25% incoming healing bonus.

**Expected behavior**
resonance adds 30% incoming healing bonus

**Screenshots**
![image](https://user-images.githubusercontent.com/67435561/113094660-12cb6500-91c0-11eb-8319-368d5b3e2560.png)

**Comment by JenShin-368** [comment]
Fixed.
