### ISSUE TITLE
Can't optimize Xinqiu

### ISSUE THREAD

**Issue by disgard** [JenShin-368/GenshinImpactCalculator#83]
**Describe the bug**
Somehow when i try to optimize Xingqiu, it doesnt works!
Like when you try to optimize his weapon/artifacts, nothing happen when click the optimize button.

**Comment by JenShin-368** [comment]
Weapons were already fixed, should be propagated by now. Artifacts are fixed (bug with new artifacts affecting all characters).

**Comment by disgard** [comment]
thanks for your hardwork, but the artifact optimization for xinqiu is seems still bugging, and now i can't optimize artifacts on razor too!
lol thats so much to ask, sorry for that.
and maybe one more, there is incostancy with weapon optimization on razor too! On default option, sometime it shows Gravesword, sometime Skyward Pride.
Thanks!

**Comment by disgard** [comment]
oh no its even on bennet, sorry i cant all of them, i cant optimize artifacts on bennet too.
i dont know what is wrong at this point.
