### ISSUE TITLE
[Premium] More Payment methods

### ISSUE THREAD

**Issue by SeppDE** [JenShin-368/GenshinImpactCalculator#84]
**Is your feature request related to a problem? Please describe.**
Unable to buy Premium cause Stripe is just accepting credit cards.

**Describe the solution you'd like**
More payment methods like Paypal for example.

**Describe alternatives you've considered**
Beeing able to donate through the "old" donate feature.

**Additional context**
Even if I'm thinking about getting a credit card for other reasons too, it would be great if there would be other payment methods like described earlier.

**Comment by JenShin-368** [comment]
Email me and we can get this figured out.  Stripe handles the subscription back-end so would need stripe to accept paypal first.
