### ISSUE TITLE
Xingqiu C4 calculated incorrectly

### ISSUE THREAD

**Issue by beta382** [JenShin-368/GenshinImpactCalculator#85]
**Describe the bug**

Xingqiu's 4th Constellation "Evilsoother" applies a 1.5x multiplier to the base damage of the skill (unlike other bonuses that factor into the additive damage bonus). See [here](https://library.keqingmains.com/mechanics/combat/damage-formula#other-bonus) for details.

However, the damage calculator's results do not reflect this. When activating Xingqiu's C4 in the damage calculator, the total skill damage increases by a fraction of the expected value. Furthermore, the absolute magnitude of this increase is the same regardless of what level his skill is set to (but is influenced by other modifiers such as additive damage increases and total ATK).

**To Reproduce**
1. Open calculator and select Xingqiu
2. Increase Constellations to 4 or higher
3. Observe that the value under Skill>Total Skill Damage did not increase by a factor of 1.5x

(Other modifiers can be selected between steps 2 and 3 and the same behavior will be observed).

**Expected behavior**
Activating Xingqiu's C4 "Evilsoother" increases his Total Skill Damage by a factor of 1.5x under all circumstances.

**Desktop**
 - OS: Windows 10 Pro 20H2
 - Browser: Chrome 90.0.4430.93

**Comment by JenShin-368** [comment]
Fixed.
