### ISSUE TITLE
Add a toggle for Xingqiu C4

### ISSUE THREAD

**Issue by beta382** [JenShin-368/GenshinImpactCalculator#86]
Xingqiu's fourth constellation "Evilsoother" conditionally increases the damage of his Elemental Skill throughout the duration of his Elemental Burst. However, there is currently no way to disable this effect other than reducing his Constellations value to below 4. 

Because the damage increase from this constellation is conditional, I would like a toggle to enable or disable its effect without needing to remove the constellation entirely. This would be consistent with how the calculator presents other constellations with conditional effects.

**Comment by JenShin-368** [comment]
Not currently possible due to the unique way this buff applies.

Fixed so that "Skill Damage" now always shows the normal skill damage (i.e. toggled off) and a "Total Skill Damage" under the constellation will show the damage when the buff is applied (i.e. toggled on).
