### ISSUE TITLE
A little mistake on Eula's Lightfall Sword damage (Physical, not Cryo)

### ISSUE THREAD

**Issue by RavenousBastard** [JenShin-368/GenshinImpactCalculator#90]
Eula's Burst consists of two parts:
1 - A wide slash that deals Cryo DMG
2 - The lightfall sword explosion that deals Physical damage.

The Genshin Calculator site is considering the lightfall sword damage as Cryo, while it should be physical.
I hope it can be fixed when possible.

Thanks for the awesome site, keep it up!

**Comment by JenShin-368** [comment]
Fixed.
