### ISSUE TITLE
Header stays in front of the main content.

### ISSUE THREAD

**Issue by sergioengineer** [JenShin-368/GenshinImpactCalculator#94]
Since the position of the header is "fixed", it stays in front of the main content as per the [screenshot.](https://snipboard.io/9IPzeK.jpg) preventing one from clicking on the character's profile in order change it for another one.

This bug only occurs in Firefox(89.0.2).(tested on both chrome and edge)

Since fixed elements don't interfere in the document's flow(https://www.w3.org/TR/CSS2/visuren.html#positioning-scheme), this behavior can be corrected by either setting the header's position to sticky( .header{ position:sticky; top:0; } ) or setting a margin for the main content.

**Comment by ChrisMGeo** [comment]
Yeah I'm getting this bug on Brave, can't click on anything.

**Comment by sergioengineer** [comment]
While the author doesn't address this by modifying the website's code, you can use greasemonkey/tampermonkey extension to create a script and change the website's style:

`// ==UserScript==
// @name     Genshin calculator fix
// @version  1
// @grant    none
// @include *genshinimpactcalculator.com*
// ==/UserScript==

{
  const header = document.querySelector(".header")

  header.style.position = "sticky"
  header.style.top = "0"

  const mainContentContainer = document.querySelector("#fullScreenContainer")
  mainContentContainer.style.marginTop = "20px"
}`

**Comment by Unyubaby** [comment]
Unblocking ads fixes it.

**Comment by sergioengineer** [comment]
Hmm, i see. I'll remove the script them. Thanks for the info.
